### ISSUE TITLE
Cannot run on Linux

### ISSUE THREAD

**Issue by Sparkenstein** [nodegui/packer#45] opened 2020-03-06 11:17 UTC
I am trying to run basic hello world app on Ubuntu 19.04. I am getting MODULE_NOT_FOUND error.
attaching the screenshot below. Is it duplicate of #29 ? 

Steps to reproduce:
- Cloned started repo with `git clone https://github.com/nodegui/nodegui-starter`
- Ran `yarn install` to install deps
- Installed packer with `yarn add -D @nodegui/packer`
- Ran packer with `yarn nodegui-packer --init MyApp`

After that I immedietly got the error
![2020-03-06_16-39](https://user-images.githubusercontent.com/24642451/76079114-00392900-5fca-11ea-9eaa-9960edd22cd4.png)

Here's pastebin of error just in case image is unreadable 
https://bin.mkr.pw/~5e623131d91d063518915d63

**Comment by master-atul** [comment] 2020-03-06 12:25
Hi @Sparkenstein 

The issue is that the packer version you are using is an alpha version (meant to be used with next release of NodeGui and is in progress)

Can you try switching to 1.1.2 of packer ?

**Comment by master-atul** [comment] 2020-03-07 12:15
Latest version of Packer along with latest version of NodeGui and react nodegui fixes this issue. 
Closing now.

**Closed by master-atul** 2020-03-07 12:15 UTC

**Comment by Sparkenstein** [comment] 2020-03-09 08:26
Yes. I tested with latest versions. it worked. 
Just a note. I faced few problems regarding cache in `~/.cache/qode-nodejs` and `~/.cache/nodegui-mini-qt-nodejs` directory. it worked after I deleted these two folders from cache. 
 
Also somehow it was working earlier without Cmake. This time, the build was failing because cmake not found. I installed with `apt install cmake` and it worked. You may wanna look into it :P

**Comment by master-atul** [comment] 2020-03-09 09:54
Yep previously it worked without cmake since there was a prebuilt version of core library which was downloaded. The latest 0.15 version doesnt have a prebuilt version due to some minor issues. This will be re enabled in future releases :)
